services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Belarus/Minsk
      - WEBUI_PORT=8080
    volumes:
      - /srv/dev-disk-by-uuid-b7ce81a0-b0cd-4aaf-9b6c-0e9c70b25431/Pub/AppData/qbittorrent:/config
      - /srv/dev-disk-by-uuid-b7ce81a0-b0cd-4aaf-9b6c-0e9c70b25431/Pub/Downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
